apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  type: LoadBalancer # hoặc NodePort để expose ra bên ngoài cluster
  ports:
    - protocol: TCP
      port: 8078       # Cổng mà Service sẽ expose ra bên ngoài
      targetPort: 8078 # Cổng mà container đang nghe trong Deployment
